# Python package
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://aka.ms/yaml
resources:
  repositories:
  - repository: templates
    type: github
    endpoint: switchcase-build
    name: SwitchCaseGroup/switchcase-azure-pipelines-templates
    ref: refs/tags/v5.8.0
  - repository: self
    clean: true

trigger:
  batch: true
  branches:
    include:
      - switchcase/bionic
  paths:
    exclude:
      - README.md
pr:
  autoCancel: true
  drafts: true

jobs:
- template: jobs/build_deb.yml@templates
  parameters:
    pool:
      vmImage: "ubuntu-18.04"
    artifactName: "switchcase-deltapatcher"
