@startuml apply-sequence

!include deltapatcher.iuml

title Binary Delta Patcher Apply Command

group initialize
  DeltaPatcher -> pch : read manifest
  DeltaPatcher -> dst : create directory structure
end

group apply
  DeltaPatcher -> XDelta3Patch : apply delta files
  activate XDelta3Patch
    XDelta3Patch -> dst : validate dst hash
    XDelta3Patch -> src : validate src hash
    XDelta3Patch -> pch : validate pch hash
    group if hash validation success
      XDelta3Patch -> xdelta3 : apply diff
      xdelta3 -> src : read file
      xdelta3 -> pch : read file
      xdelta3 -> dst : read file
      xdelta3 -> dst : write file
    end
    group else (hash validation failure)
      XDelta3Patch -> HTTP : download dst file(s)
    end
  return return src/dst/pch hashes
end

group finalize
  DeltaPatcher -> dst : remove obsolete files/dirs
  DeltaPatcher -> dst : apply file properties
end

@enduml
